### ISSUE TITLE
Gapseq GEMs, 16S QIIME data, western diet

### ISSUE THREAD

**Issue by TKuehnast** [micom-dev/q2-micom#18] opened 2022-08-02 14:29 UTC
Hi,

I want to run simulations with MICOM, using my own little catalogue of gapseq GEMs (instead of AGORA) and combine it with my 16S data. Western diet is currently used as placeholder.

This catalogue was created by running gapseq on 160 selected bacterial chromosomes, and creating "our160_genus.qza" from the resulting .xmls files via qiime.

Creating a model worked:

qiime micom build --i-abundance table-dada2.qza \
                  --i-taxonomy taxonomy.qza \
                  --i-models our160_genus.qza \
                  --p-cutoff 0.0001 \
                  --p-threads 6 \
                  --o-community-models our160_models.qza \

When I want to use the model for tradeoff:

qiime micom tradeoff --i-models our160_models.qza \
                     --i-medium western_diet_gut.qza \
                     --p-threads 6 \
                     --o-results our160_tradeoff.qza \

An error comes:

```
Running ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/micom/workflows/tradeoff.py", line 23, in _tradeoff
    com.medium = medium[medium.index.isin(ex_ids)]
  File "/home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/micom/community.py", line 663, in medium
    raise ValueError(
ValueError: No ID from the medium could be found in the exchange reactions. This means you probably have mismatched IDs...
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/q2cli/commands.py", line 339, in __call__
    results = action(**arguments)
  File "<decorator-gen-464>", line 2, in tradeoff
  File "/home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    outputs = self._callable_executor_(scope, callable_args,
  File "/home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/qiime2/sdk/action.py", line 391, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/q2_micom/_tradeoff.py", line 27, in tradeoff
    results = mw.tradeoff(manifest, model_folder, medium, tradeoffs, threads)
  File "/home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/micom/workflows/tradeoff.py", line 111, in tradeoff
    results = workflow(_tradeoff, args, threads)
  File "/home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/micom/workflows/core.py", line 55, in workflow
    results = list(it)
  File "/home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/rich/progress.py", line 166, in track
    yield from progress.track(
  File "/home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/rich/progress.py", line 1119, in track
    for value in sequence:
  File "/home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
ValueError: No ID from the medium could be found in the exchange reactions. This means you probably have mismatched IDs...

Plugin error from micom:

  No ID from the medium could be found in the exchange reactions. This means you probably have mismatched IDs...

See above for debug info.
```

Running the same files, however with AGORA or Carveme catalogue instead of my own, I get functional tradeoff files. 

In an earlier version I just used 20 instead of 160 GEMs, but the same error appeared.

I am using the versions:
gapseq version: 1.2 ccd1144
Qiime2-2022.02.
micom: 0.12.1

Best,

**Comment by cdiener** [comment] 2022-08-02 19:32
Hi, yes that is expected due to different databases using different IDs for metabolites. For instance within AGORA Glucose has the ID `glc__D` and in gapseq it has the ID `cpd00027`. Those issues probably also arose when using CARVEME models, just that MICOM can not easily detect them there since some (but not all) metabolites have the same names in CARVEME and AGORA. 

So one can not generally use media between different model databases. We are working on adding some gapseq model databases and a translation function to convert media between those. However, you can convert the [media from the Gapseq repository](https://github.com/jotech/gapseq/tree/master/dat/media) to MICOM format. Here is some example code that does this for the Gapseq "gut" medium.

```bash
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pandas as pd

In [2]: import qiime2 as q2

In [3]: gapseq_medium = pd.read_csv("gut.csv")

In [4]: gapseq_medium.columns = ["metabolite", "name", "flux"]

In [5]: gapseq_medium["reaction"] = "EX_" + gapseq_medium.metabolite + "_m"

In [6]: arti = q2.Artifact.import_data("MicomMedium[Global]", gapseq_medium)

In [7]: arti.save("gapseq_gut_medium.qza")
Out[7]: 'gapseq_gut_medium.qza'
```

Just make sure that all of your Gapseq models have been gapfilled on the medium you are converting, otherwise it will not work.

Best

**Comment by TKuehnast** [comment] 2022-08-03 14:23
Thank you greatly for your quick and detailed feedback, helped me a lot. Will report about my solutions once finished.

Best.

**Comment by TKuehnast** [comment] 2022-08-23 13:32
I am still trying to incorporate my gapseq-based database into micom:
```
from micom.workflows import grow

res = grow(manifest, model_folder="models_Our160_genus_py", medium=medium, tradeoff=0.5, threads=2)
```
While I am digging deep into micom's code and tracing the error, do you possibly have a spare moment for a hint what this error is about?
`ValueError: Length of values (27656) does not match length of index (24364)`


```
ValueError                                Traceback (most recent call last)
Input In [11], in <module>
      1 from micom.workflows import grow
----> 3 res = grow(manifest, model_folder="models_Our160_genus_py", medium=medium, tradeoff=0.5, threads=2)

File /home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/micom/workflows/grow.py:211, in grow(manifest, model_folder, medium, tradeoff, threads, weights, strategy, atol, rtol, presolve)
    207 anns = pd.concat(
    208     r["annotations"] for r in results if r is not None
    209 ).drop_duplicates()
    210 anns.index = anns.reaction
--> 211 exchanges["metabolite"] = anns.loc[exchanges.reaction, "metabolite"].values
    212 exchanges["direction"] = DIRECTION[(exchanges.flux > 0.0).astype(int)].values
    213 exchanges = exchanges[exchanges.flux.abs() > exchanges.tolerance]

File /home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/pandas/core/frame.py:3163, in DataFrame.__setitem__(self, key, value)
   3160     self._setitem_array(key, value)
   3161 else:
   3162     # set column
-> 3163     self._set_item(key, value)

File /home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/pandas/core/frame.py:3242, in DataFrame._set_item(self, key, value)
   3232 """
   3233 Add series to DataFrame in specified column.
   3234 
   (...)
   3239 ensure homogeneity.
   3240 """
   3241 self._ensure_valid_index(value)
-> 3242 value = self._sanitize_column(key, value)
   3243 NDFrame._set_item(self, key, value)
   3245 # check if we are modifying a copy
   3246 # try to set first as we want an invalid
   3247 # value exception to occur first

File /home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/pandas/core/frame.py:3899, in DataFrame._sanitize_column(self, key, value, broadcast)
   3894     value = sanitize_index(value, self.index)
   3896 elif isinstance(value, Index) or is_sequence(value):
   3897 
   3898     # turn me into an ndarray
-> 3899     value = sanitize_index(value, self.index)
   3900     if not isinstance(value, (np.ndarray, Index)):
   3901         if isinstance(value, list) and len(value) > 0:

File /home/conda/miniconda3/envs/qiime2-2022.2/lib/python3.8/site-packages/pandas/core/internals/construction.py:751, in sanitize_index(data, index)
    746 """
    747 Sanitize an index type to return an ndarray of the underlying, pass
    748 through a non-Index.
    749 """
    750 if len(data) != len(index):
--> 751     raise ValueError(
    752         "Length of values "
    753         f"({len(data)}) "
    754         "does not match length of index "
    755         f"({len(index)})"
    756     )
    758 if isinstance(data, np.ndarray):
    759 
    760     # coerce datetimelike types
    761     if data.dtype.kind in ["M", "m"]:

ValueError: Length of values (27656) does not match length of index (24364)
```

**Comment by cdiener** [comment] 2022-08-23 14:12
Hmm looks like you have a few reactions that have the same name but different reactants across models. How were those models created? Are they all gapseq models built with the same gapseq version?

**Comment by TKuehnast** [comment] 2022-08-23 14:29
The gapseq models are indeed created within a few days on the same version.
"gapseq version":"1.2 ccd1144; Sequence DB md5sum: 1139b8e (2022-02-24, Bacteria)"
"gapseq version":"1.2 ccd1144; Sequence DB md5sum: 1139b8e (2022-02-24, Bacteria)"
"gapseq version":"1.2 ccd1144; Sequence DB md5sum: 1139b8e (2022-02-24, Bacteria)"
"gapseq version":"1.2 ccd1144; Sequence DB md5sum: 1139b8e (2022-02-24, Bacteria)"

I am not sure about the gut.csv you recommended directly from gapseq github. I modified it according to your script.

Maybe they dont fit together?

**Comment by cdiener** [comment] 2022-08-23 15:02
Hmm, hard to say what is going on exactly without seeing the models, but I will make a Bugfix that checks for that issue and handles it in the meanwhile. We are currently building a model database based on UHGG for MICOM so I will check whether I can reproduce the issue there when it's done.

**Comment by TKuehnast** [comment] 2022-08-24 08:54
I attached my files, if you want to have a look.

Log:

Genomes --> gapseq version: 1.2 ccd1144 --> *.xml files --> Qiime2-2022.02. --> gap_reconst_genus_py.qza

Diet --> gut.csv from https://github.com/jotech/gapseq/blob/master/dat/media/gut.csv, modified according to your jupyter steps (see above) --> gapseq_gut_medium.csv

Taxonomy and abundance from 16S via --> Qiime2-2021.2.0. Modified according to micom protocol to contain id, genus, sample_id and abundance --> taxa_table_py_crop_fake.csv
[Upload TK_v001.zip](https://github.com/micom-dev/q2-micom/files/9414498/Upload.TK_v001.zip)

Current environment: Qiime2-2022.02 + micom: 0.12.1 via jupyter notebook

**Comment by cdiener** [comment] 2022-08-24 14:52
Awesome, thanks so much. That will be very helpful to pinpoint the issue!

**Comment by cdiener** [comment] 2022-08-25 19:28
I ran your example with the current version of micom and it ran fine. After that I saw that I pushed a bunch of fixes for annotation merging in February. So updating micom to 0.30.5 shoulf fix that for you. Just running `pip install -U micom` in your environment should be sufficient.

**Comment by cdiener** [comment] 2022-08-30 21:09
Closing for now. Let me know if the issue persists after updating MICOM.

**Closed by cdiener** 2022-08-30 21:09 UTC
